# Generated by Django 5.1.1 on 2024-09-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_imagemodel_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('hodim_fish', models.CharField(max_length=255)),
                ('sana', models.DateField()),
                ('viloyat', models.CharField(max_length=255)),
                ('tuman', models.CharField(max_length=255)),
                ('aloqa_bolimi_nomi', models.CharField(max_length=255)),
                ('rasm', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
