# Generated by Django 5.1.1 on 2024-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_record_delete_imagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rasm',
        ),
        migrations.AlterField(
            model_name='record',
            name='sana',
            field=models.DateField(auto_now_add=True),
        ),
    ]
