# Generated by Django 5.1.1 on 2024-09-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_record_rasm_alter_record_sana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sana',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
