# Generated by Django 5.1.1 on 2024-09-16 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_record_sana'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='rasm',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='record',
            name='sana',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
